### PR TITLE
[Feature] Explanation section with ollama

### LINKED ISSUE #17: [Feature] Explanation section
Simply create such a section as part of the repo codebase and add it (however you wish) to the repo. Flexible with solution.

On one side, it might be problematic to add explanations to the platform education.ditectrev.com **without** having them in the repository. However, having them somehow dynamically would be the preferred solution, without relying on the repositories content. 
Why? We have thousands of questions, and it'd be lots of work to add explanation to every single question, and only then fetch the results, and show them on the platform education.ditectrev.com

However, on the long run, it'd be great to have the explanations in the repository, so students could learn also from GitHub content.
Having a script, which would generate explanations easy to add to the format we already use in other tests:

```
### QUESTION X

![Image](images/questionX.png)

- [ ] Wrong Answer.
- [x] Correct Answer.
- [ ] Wrong Answer.
- [ ] Wrong Answer.

#### [TODO] EXPLANATION GOES HERE...

**[⬆ Back to Top](#table-of-contents)**
```

### PR DESCRIPTION
**Pull request by emilosman**
[Fixes #17](https://github.com/Ditectrev/Practice-Exams-Platform/issues/17)

Screenshot 2024-05-12 at 18 44 28

_wip layout_

## Summary
- Adds a button that prompts a locally running [ollama](https://ollama.com/) server to explain the correct answers to the question.
- The prompt consists of the question and answers, giving as much context as possible for the LLM.

## CORS
When the app is deployed to production, your locally running ollama should be started with this option:
`OLLAMA_ORIGINS="https://education.ditectrev.com" ollama serve`

## Todo
- [x] Check whether ollama is running
- [x] Fine-tune prompt
- [ ] ollama options (currently `mistral` is the hard-coded model)
- [x] Improve layout of buttons and answers
- [x] Remove debug code
- [ ] Tests

### CODE REVIEW

**Comment by danieldanielecki** [comment]
as we discussed on Discord:
1. Let's keep the UI you've developed for the explanation section (feel free to improve ofc!).
2. Tweak the Ollama script to Python as described in https://github.com/Ditectrev/Automation-Tools-for-Courses/issues/4 and submit PR there. We'll generate static content for explanations, and deploy it. It'll limit the number of calls (esp. if it'd potentially scale traffic-wise), and fix the problem of hosting. As you guys correctly noticed on Discord: regenerating explanations for a set of questions that don't change frequently doesn't really make sense.
3. Adding a feature to rate the explanation is welcome, feel free to do so, and the PR will be approved.

**Comment by danieldanielecki** [comment]
@emilosman shall I merge it & would you be so kind to create a Python script to have static content generated as explained in https://github.com/Ditectrev/Automation-Tools-for-Courses/issues/4?

**Comment by emilosman** [comment]
@danieldanielecki I'll look into creating a script to generate and save explanations. I'll keep you updated.
You can merge it if you want this feature and are ok with the implementation.

**Comment by danieldanielecki** [comment]
It'd be good to add information about how to run `Ollama`: https://webinstall.dev/ollama/. It took me 20 minutes or so to figure out. Great job tho, merging.

**Comment by danieldanielecki** [comment]
3 improvements I see:
1. Add it to the Practice Exams as well.
2. Layout indeed, as per your screenshot note.
3. When Ollama runs without a Mistral installed then it still shows the `Explain` button.

What running `OLLAMA_ORIGINS="https://education.ditectrev.com" ollama serve` gives actually?
The user needs to have the repository locally anyway in order to see the explanation section.

**Pull request merged**
